name: 🚀 Release

on:
  push:
    tags:
      - 'v*.*'

permissions:
  contents: write

jobs:
  build-artifacts:
    uses: ./.github/workflows/build.yml

  create-release:
    needs: build-artifacts
    env:
      GH_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Download Build Artifacts
        uses: actions/download-artifact@v5

      - run: ls
      - run: ls -R artifacts/

      - name: Generate New Release
        run: |
          gh release create ${{ github.ref }} ./artifacts/*
