name: Test by Dogfood

on:
  workflow_call:
  push:
    branches:
      - main

jobs:
  build-artifact:
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest, macos-latest]
        os: [windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: jiro4989/setup-nim-action@v2
      - uses: goto-bus-stop/setup-zig@v2

      - name: Bootstrap with installed version
        run: |
          nimble install -Y
          mv C:\Users\runneradmin\.nimble\bin\forge.cmd C:\Users\runneradmin\.nimble\bin\forge.exe

      - run: |
          (Get-Command forge).Path
          forge +targets

      - run: nimble setup -l
      - run: |
          nim c --cpu:arm64 --os:Linux --cc:clang --clang.exe=forge --clang.linkerexe=forge --passC:'-target aarch64-linux-gnu' --passL:'-target aarch64-linux-gnu' -d:release --outdir:"dist\forge-v2025.1006-aarch64-linux-gnu" "src\forge"

      - name: Generate all build artifacts
        run: |
          nimble setup -l
          forge +release --verbose
